import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import BottomNav from "@/components/shared/BottomNav";
import Header from "@/components/shared/Header";
import ScrollToTop from "@/components/ScrollToTop";
import TelegramWebApp from "@/components/TelegramWebApp";

export const metadata: Metadata = {
  title: "Cars Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* Telegram Web App SDK */}
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
        <TelegramWebApp />
        <Header />
        <main className="pt-20">{children}</main>
        <BottomNav />
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
