import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import BottomNav from "@/components/shared/BottomNav";
import Header from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Cars Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="pt-20" >{children}</main>
        <BottomNav />
        <Footer />
      </body>
    </html>
  );
}
